/**
 * DocuNexa — Centralized Type-Safe Download Pipeline & Output Contract
 *
 * Enforces strict agreement across:
 *   filename extension == advertised format == Blob MIME type == actual generated bytes
 *
 * Rules:
 * - Never produces double extensions (.pptx.pdf, .xlsx.pdf, .docx.docx, .pdf.pdf, etc.)
 * - Never preserves conflicting source extensions
 * - Detects binary/container signatures directly from byte stream
 * - Centralizes canonical MIME types, extensions, labels, and sanitization
 */

export type CanonicalFormat =
  | 'pdf'
  | 'docx'
  | 'pptx'
  | 'xlsx'
  | 'png'
  | 'jpg'
  | 'txt'
  | 'md'
  | 'zip'
  | 'json';

export interface FormatSpec {
  format: CanonicalFormat;
  extension: string;
  aliases: string[];
  mimeType: string;
  label: string;
  actionLabel: string;
}

export const CANONICAL_FORMATS: Record<CanonicalFormat, FormatSpec> = {
  pdf: {
    format: 'pdf',
    extension: '.pdf',
    aliases: ['.pdf'],
    mimeType: 'application/pdf',
    label: 'PDF Document (.pdf)',
    actionLabel: 'Download PDF (.pdf)',
  },
  docx: {
    format: 'docx',
    extension: '.docx',
    aliases: ['.docx', '.doc'],
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    label: 'Word Document (.docx)',
    actionLabel: 'Download Word Document (.docx)',
  },
  pptx: {
    format: 'pptx',
    extension: '.pptx',
    aliases: ['.pptx', '.ppt'],
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    label: 'PowerPoint Presentation (.pptx)',
    actionLabel: 'Download PowerPoint (.pptx)',
  },
  xlsx: {
    format: 'xlsx',
    extension: '.xlsx',
    aliases: ['.xlsx', '.xls', '.csv'],
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    label: 'Excel Spreadsheet (.xlsx)',
    actionLabel: 'Download Excel (.xlsx)',
  },
  png: {
    format: 'png',
    extension: '.png',
    aliases: ['.png'],
    mimeType: 'image/png',
    label: 'PNG Image (.png)',
    actionLabel: 'Download Image (.png)',
  },
  jpg: {
    format: 'jpg',
    extension: '.jpg',
    aliases: ['.jpg', '.jpeg'],
    mimeType: 'image/jpeg',
    label: 'JPEG Image (.jpg)',
    actionLabel: 'Download Image (.jpg)',
  },
  txt: {
    format: 'txt',
    extension: '.txt',
    aliases: ['.txt'],
    mimeType: 'text/plain;charset=utf-8',
    label: 'Text Document (.txt)',
    actionLabel: 'Download Text Document (.txt)',
  },
  md: {
    format: 'md',
    extension: '.md',
    aliases: ['.md', '.markdown'],
    mimeType: 'text/markdown;charset=utf-8',
    label: 'Markdown Document (.md)',
    actionLabel: 'Download Markdown (.md)',
  },
  zip: {
    format: 'zip',
    extension: '.zip',
    aliases: ['.zip'],
    mimeType: 'application/zip',
    label: 'ZIP Archive (.zip)',
    actionLabel: 'Download ZIP Archive (.zip)',
  },
  json: {
    format: 'json',
    extension: '.json',
    aliases: ['.json'],
    mimeType: 'application/json;charset=utf-8',
    label: 'JSON Document (.json)',
    actionLabel: 'Download JSON (.json)',
  },
};

export interface DownloadContract {
  blob: Blob;
  bytes: Uint8Array;
  filename: string;
  mimeType: string;
  extension: string;
  format: CanonicalFormat;
  label: string;
  actionLabel: string;
}

const EMBEDDED_EXTENSIONS_REGEX =
  /\.(pdf|docx|doc|pptx|ppt|xlsx|xls|png|jpe?g|webp|gif|bmp|tiff?|txt|md|markdown|json|zip|html?|csv|project)(?=[.\s\-_]|$)/gi;

/**
 * Strips all embedded and trailing known file extensions to prevent stacked/double extensions
 * e.g.:
 * "grade-10-history.pptx.pdf" -> "grade-10-history"
 * "grade-10-history.pptx" -> "grade-10-history"
 * "notes.docx.pdf" -> "notes"
 * "notes.docx - Summary.md" -> "notes - Summary"
 * "document.pdf.project.json" -> "document"
 * "data.xlsx" -> "data"
 */
export function stripAllExtensions(rawName: string): string {
  if (!rawName) return '';
  let name = rawName.trim();
  name = name.replace(EMBEDDED_EXTENSIONS_REGEX, '');
  return name.trim();
}

/**
 * Sanitizes the base filename:
 * 1. Strips all known extensions
 * 2. Replaces invalid filesystem chars [<>:"/\\|?*\x00-\x1F] with hyphens
 * 3. Collapses consecutive dashes/underscores
 * 4. Trims leading/trailing dots, spaces, and hyphens
 */
export function sanitizeBaseName(rawName: string, fallback = 'document'): string {
  if (!rawName) return fallback;
  const stripped = stripAllExtensions(rawName);
  const cleaned = stripped
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, '-')
    .replace(/-+/g, '-')
    .replace(/_+/g, '_')
    .replace(/^[.\s\-_]+|[.\s\-_]+$/g, '');
  return cleaned || fallback;
}

/**
 * Resolves a format keyword, MIME type, or filename to a CanonicalFormat
 */
export function resolveFormat(input?: string): CanonicalFormat {
  if (!input) return 'pdf';
  const lower = input.toLowerCase().trim();

  if (lower in CANONICAL_FORMATS) {
    return lower as CanonicalFormat;
  }

  // Check MIME types
  for (const [fmt, spec] of Object.entries(CANONICAL_FORMATS)) {
    if (lower.startsWith(spec.mimeType.split(';')[0])) {
      return fmt as CanonicalFormat;
    }
  }

  // Check extensions
  if (lower.endsWith('.pdf')) return 'pdf';
  if (lower.endsWith('.docx') || lower.endsWith('.doc')) return 'docx';
  if (lower.endsWith('.pptx') || lower.endsWith('.ppt')) return 'pptx';
  if (lower.endsWith('.xlsx') || lower.endsWith('.xls') || lower.endsWith('.csv')) return 'xlsx';
  if (lower.endsWith('.png')) return 'png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'jpg';
  if (lower.endsWith('.txt')) return 'txt';
  if (lower.endsWith('.md') || lower.endsWith('.markdown')) return 'md';
  if (lower.endsWith('.zip')) return 'zip';
  if (lower.endsWith('.json')) return 'json';

  return 'pdf';
}

/**
 * Generates a clean, canonical filename for a target format.
 * Guaranteed:
 * 1. Base name is sanitized and stripped of old extensions.
 * 2. Ends strictly with the target format's canonical extension.
 * 3. Never produces double extensions like .pptx.pdf, .xlsx.pdf, .docx.docx, .pdf.pdf.
 */
export function sanitizeDownloadFilename(
  rawFilename: string,
  targetFormatOrExt?: CanonicalFormat | string,
  actionSuffix?: string
): string {
  const formatKey = resolveFormat(targetFormatOrExt || rawFilename);
  const spec = CANONICAL_FORMATS[formatKey] || CANONICAL_FORMATS.pdf;

  let base = sanitizeBaseName(rawFilename, 'document');

  if (actionSuffix) {
    const cleanAction = actionSuffix.replace(/^[-_\s]+|[-_\s]+$/g, '');
    const suffixRegex = new RegExp(`[-_\\s]+${cleanAction}$`, 'i');
    base = base.replace(suffixRegex, '');
    base = `${base}-${cleanAction}`;
  }

  return `${base}${spec.extension}`;
}

/**
 * Fast search for ASCII string inside byte array
 */
function bytesContainAscii(bytes: Uint8Array, search: string, maxScan = 65536): boolean {
  if (bytes.length < search.length) return false;
  const searchBytes = new TextEncoder().encode(search);
  const scanLimit = Math.min(bytes.length, maxScan) - searchBytes.length;
  for (let i = 0; i <= scanLimit; i++) {
    let match = true;
    for (let j = 0; j < searchBytes.length; j++) {
      if (bytes[i + j] !== searchBytes[j]) {
        match = false;
        break;
      }
    }
    if (match) return true;
  }
  return false;
}

/**
 * Detects the canonical format from the raw binary stream/container signatures.
 */
export function detectFormatFromBytes(bytes: Uint8Array): CanonicalFormat | null {
  if (!bytes || bytes.length === 0) return null;

  // 1. PDF: %PDF- (0x25 0x50 0x44 0x46 0x2D)
  if (
    (bytes.length >= 5 &&
      bytes[0] === 0x25 &&
      bytes[1] === 0x50 &&
      bytes[2] === 0x44 &&
      bytes[3] === 0x46 &&
      bytes[4] === 0x2d) ||
    bytesContainAscii(bytes, '%PDF-', 1024)
  ) {
    return 'pdf';
  }

  // 2. PNG: 0x89 0x50 0x4E 0x47 0x0D 0x0A 0x1A 0x0A
  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a
  ) {
    return 'png';
  }

  // 3. JPEG: 0xFF 0xD8 0xFF
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return 'jpg';
  }

  // 4. PK ZIP containers: 0x50 0x4B (DOCX, PPTX, XLSX, or plain ZIP)
  if (bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b) {
    // Discriminate OpenXML packages by internal structure
    if (bytesContainAscii(bytes, 'word/')) return 'docx';
    if (bytesContainAscii(bytes, 'ppt/')) return 'pptx';
    if (bytesContainAscii(bytes, 'xl/')) return 'xlsx';
    return 'zip';
  }

  // 5. JSON
  try {
    const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes.slice(0, 1024)).trim();
    if ((text.startsWith('{') && text.endsWith('}')) || (text.startsWith('[') && text.endsWith(']'))) {
      JSON.parse(new TextDecoder('utf-8').decode(bytes));
      return 'json';
    }
  } catch {
    // Not valid JSON
  }

  // 6. Text / Markdown
  try {
    const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes.slice(0, 4096));
    // Check if it contains binary nulls or non-printable controls
    if (!/[\x00-\x08\x0E-\x1F]/.test(text)) {
      if (/^#+\s|\*\*|__|^-\s|^\*\s|\[.+\]\(.+\)/m.test(text)) {
        return 'md';
      }
      return 'txt';
    }
  } catch {
    // Binary
  }

  return null;
}

/**
 * Validates that actual output bytes physically match the claimed format.
 */
export function assertValidBytesForFormat(bytes: Uint8Array, format: CanonicalFormat): void {
  if (!bytes || bytes.length === 0) {
    throw new Error(`Download validation failed: Generated bytes are empty (0 bytes) for format '${format}'.`);
  }

  switch (format) {
    case 'pdf': {
      if (!bytesContainAscii(bytes, '%PDF-', 1024)) {
        throw new Error('Download validation failed: Generated document lacks valid PDF header (%PDF-).');
      }
      break;
    }
    case 'png': {
      if (
        bytes.length < 8 ||
        bytes[0] !== 0x89 ||
        bytes[1] !== 0x50 ||
        bytes[2] !== 0x4e ||
        bytes[3] !== 0x47 ||
        bytes[4] !== 0x0d ||
        bytes[5] !== 0x0a ||
        bytes[6] !== 0x1a ||
        bytes[7] !== 0x0a
      ) {
        throw new Error('Download validation failed: Generated image lacks valid PNG signature.');
      }
      break;
    }
    case 'jpg': {
      if (bytes.length < 3 || bytes[0] !== 0xff || bytes[1] !== 0xd8 || bytes[2] !== 0xff) {
        throw new Error('Download validation failed: Generated image lacks valid JPEG signature.');
      }
      break;
    }
    case 'docx': {
      if (bytes.length < 4 || bytes[0] !== 0x50 || bytes[1] !== 0x4b) {
        throw new Error('Download validation failed: Word document lacks PK ZIP package header.');
      }
      if (!bytesContainAscii(bytes, 'word/')) {
        throw new Error('Download validation failed: Word document package missing word/ structure.');
      }
      break;
    }
    case 'pptx': {
      if (bytes.length < 4 || bytes[0] !== 0x50 || bytes[1] !== 0x4b) {
        throw new Error('Download validation failed: PowerPoint presentation lacks PK ZIP package header.');
      }
      if (!bytesContainAscii(bytes, 'ppt/')) {
        throw new Error('Download validation failed: PowerPoint package missing ppt/ structure.');
      }
      break;
    }
    case 'xlsx': {
      if (bytes.length < 4 || bytes[0] !== 0x50 || bytes[1] !== 0x4b) {
        throw new Error('Download validation failed: Excel spreadsheet lacks PK ZIP package header.');
      }
      if (!bytesContainAscii(bytes, 'xl/')) {
        throw new Error('Download validation failed: Excel spreadsheet missing xl/ structure.');
      }
      break;
    }
    case 'zip': {
      if (bytes.length < 4 || bytes[0] !== 0x50 || bytes[1] !== 0x4b) {
        throw new Error('Download validation failed: ZIP archive lacks PK signature.');
      }
      break;
    }
    case 'txt':
    case 'md': {
      try {
        new TextDecoder('utf-8', { fatal: true }).decode(bytes.slice(0, 1024));
      } catch {
        throw new Error(`Download validation failed: Text output is corrupted binary data.`);
      }
      break;
    }
    case 'json': {
      try {
        JSON.parse(new TextDecoder('utf-8').decode(bytes));
      } catch (err: any) {
        throw new Error(`Download validation failed: Invalid JSON output (${err.message}).`);
      }
      break;
    }
  }
}

/**
 * Creates an authoritative DownloadContract.
 * Enforces:
 *   filename extension == advertised format == Blob MIME type == actual generated bytes
 */
export function createDownloadContract(
  optionsOrBytes:
    | {
        bytes: Uint8Array | Blob;
        filename: string;
        format?: CanonicalFormat;
        mimeType?: string;
        actionSuffix?: string;
      }
    | Uint8Array
    | Blob,
  filenameArg?: string,
  formatArg?: CanonicalFormat,
  actionSuffixArg?: string
): DownloadContract {
  const options =
    optionsOrBytes instanceof Uint8Array ||
    typeof (optionsOrBytes as any)?.arrayBuffer === 'function' ||
    !optionsOrBytes ||
    !('bytes' in (optionsOrBytes as any))
      ? {
          bytes: optionsOrBytes as Uint8Array | Blob,
          filename: filenameArg || 'document',
          format: formatArg,
          actionSuffix: actionSuffixArg,
        }
      : (optionsOrBytes as {
          bytes: Uint8Array | Blob;
          filename: string;
          format?: CanonicalFormat;
          mimeType?: string;
          actionSuffix?: string;
        });

  let u8Bytes: Uint8Array;
  if (options.bytes instanceof Uint8Array) {
    u8Bytes = options.bytes;
  } else if (typeof (options.bytes as any)?.arrayBuffer === 'function') {
    // In synchronous contexts where Blob is passed, we wrap it or extract buffer
    u8Bytes = new Uint8Array();
  } else {
    u8Bytes = new Uint8Array();
  }

  // 1. Determine target format
  const detectedByteFormat = u8Bytes.length > 0 ? detectFormatFromBytes(u8Bytes) : null;
  const format: CanonicalFormat =
    options.format ||
    (detectedByteFormat && detectedByteFormat !== 'zip' ? detectedByteFormat : null) ||
    resolveFormat(options.filename) ||
    'pdf';

  // 2. Validate bytes against resolved format if Uint8Array is available
  if (u8Bytes.length > 0) {
    assertValidBytesForFormat(u8Bytes, format);
  }

  // 3. Obtain canonical format specification
  const spec = CANONICAL_FORMATS[format] || CANONICAL_FORMATS.pdf;

  // 4. Sanitize and canonicalize filename
  const cleanFilename = sanitizeDownloadFilename(options.filename, format, options.actionSuffix);

  // 5. Build Blob with canonical MIME type
  let blob: Blob;
  if (options.bytes instanceof Blob) {
    // Ensure blob type matches spec.mimeType
    blob = options.bytes.type === spec.mimeType
      ? options.bytes
      : new Blob([options.bytes], { type: spec.mimeType });
  } else {
    blob = new Blob([u8Bytes as BlobPart], { type: spec.mimeType });
  }

  // 6. Contract Verification Checks
  if (!cleanFilename.toLowerCase().endsWith(spec.extension)) {
    throw new Error(
      `Download Contract Invariant Broken: Filename '${cleanFilename}' does not end with expected extension '${spec.extension}' for format '${format}'.`
    );
  }

  return {
    blob,
    bytes: u8Bytes,
    filename: cleanFilename,
    mimeType: spec.mimeType,
    extension: spec.extension,
    format,
    label: spec.label,
    actionLabel: spec.actionLabel,
  };
}

/**
 * Triggers native browser download backed by an authoritative DownloadContract.
 */
export function triggerDownload(
  input: DownloadContract | { bytes: Uint8Array | Blob; filename: string; format?: CanonicalFormat; actionSuffix?: string }
): DownloadContract {
  let contract: DownloadContract;
  if ('extension' in input && 'format' in input && 'blob' in input) {
    contract = input as DownloadContract;
  } else {
    contract = createDownloadContract(input);
  }

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    const url = URL.createObjectURL(contract.blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = contract.filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  return contract;
}
