import { ToolCategory, ToolCategoryInfo, ToolItem } from '@/types';

export const TOOL_CATEGORIES: ToolCategoryInfo[] = [
  {
    id: 'organize',
    name: 'Organize PDF',
    tagline: 'Merge, split, cut, extract, and reorder document pages',
    accentColor: 'rose',
    accentBg: 'bg-rose-50 dark:bg-rose-950/30',
    accentBorder: 'border-rose-200 dark:border-rose-800/50',
    accentText: 'text-rose-600 dark:text-rose-400',
  },
  {
    id: 'optimize',
    name: 'Optimize PDF',
    tagline: 'Compress, repair, and OCR scanned document pages',
    accentColor: 'emerald',
    accentBg: 'bg-emerald-50 dark:bg-emerald-950/30',
    accentBorder: 'border-emerald-200 dark:border-emerald-800/50',
    accentText: 'text-emerald-600 dark:text-emerald-400',
  },
  {
    id: 'convert-to',
    name: 'Convert to PDF',
    tagline: 'Transform images, Office docs, and HTML into PDFs',
    accentColor: 'amber',
    accentBg: 'bg-amber-50 dark:bg-amber-950/30',
    accentBorder: 'border-amber-200 dark:border-amber-800/50',
    accentText: 'text-amber-600 dark:text-amber-400',
  },
  {
    id: 'convert-from',
    name: 'Convert from PDF',
    tagline: 'Export PDFs to JPG, Word, Excel, PPTX, and PDF/A',
    accentColor: 'blue',
    accentBg: 'bg-blue-50 dark:bg-blue-950/30',
    accentBorder: 'border-blue-200 dark:border-blue-800/50',
    accentText: 'text-blue-600 dark:text-blue-400',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    tagline: 'Rotate, crop, watermark, number, and annotate pages',
    accentColor: 'purple',
    accentBg: 'bg-purple-50 dark:bg-purple-950/30',
    accentBorder: 'border-purple-200 dark:border-purple-800/50',
    accentText: 'text-purple-600 dark:text-purple-400',
  },
  {
    id: 'security',
    name: 'PDF Security',
    tagline: 'Encrypt, unlock, digitally sign, redact, and compare',
    accentColor: 'cyan',
    accentBg: 'bg-sky-50 dark:bg-sky-950/30',
    accentBorder: 'border-sky-200 dark:border-sky-800/50',
    accentText: 'text-sky-600 dark:text-sky-400',
  },
  {
    id: 'intelligence',
    name: 'PDF Intelligence',
    tagline: 'AI document summaries, translation, and Markdown exports',
    accentColor: 'indigo',
    accentBg: 'bg-indigo-50 dark:bg-indigo-950/30',
    accentBorder: 'border-indigo-200 dark:border-indigo-800/50',
    accentText: 'text-indigo-600 dark:text-indigo-400',
  },
];

export const ALL_TOOLS: ToolItem[] = [
  // ---------------- ORGANIZE PDF ----------------
  {
    id: 'pdf-unit-cutter',
    name: 'PDF Unit Cutter',
    slug: 'pdf-unit-cutter',
    category: 'organize',
    description: 'Automatically detect textbook units, chapters, and TOC to split into structured PDFs.',
    iconName: 'Scissors',
    badge: 'Featured',
    isFlagship: true,
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['unit', 'cutter', 'textbook', 'chapter', 'syllabus', 'split', 'toc', 'automatic'],
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split-pdf',
    category: 'organize',
    description: 'Split a PDF into custom page ranges or separate individual pages into separate files.',
    iconName: 'Split',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['split', 'cut', 'separate', 'pages', 'divide', 'range'],
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    category: 'organize',
    description: 'Combine multiple PDF documents into a single organized file in your preferred order.',
    iconName: 'Files',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['merge', 'combine', 'join', 'append', 'concatenate'],
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    slug: 'remove-pages',
    category: 'organize',
    description: 'Select and delete unwanted or blank pages from your PDF document in seconds.',
    iconName: 'Trash2',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['remove', 'delete', 'cut', 'blank', 'pages', 'trim'],
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    slug: 'extract-pages',
    category: 'organize',
    description: 'Select specific pages from a PDF to generate a new standalone document.',
    iconName: 'FileSpreadsheet',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['extract', 'select', 'pull', 'isolate', 'subset'],
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    slug: 'organize-pdf',
    category: 'organize',
    description: 'Drag and reorder page thumbnails, rotate individual sheets, and discard pages.',
    iconName: 'LayoutGrid',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['organize', 'reorder', 'sort', 'arrange', 'thumbnails'],
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    slug: 'scan-to-pdf',
    category: 'organize',
    description: 'Use your camera or document scanner to capture pages and convert them into a PDF.',
    iconName: 'ScanLine',
    clientSide: true,
    supportedInputTypes: ['image/*', '.pdf'],
    keywords: ['scan', 'camera', 'capture', 'photo', 'scanner'],
  },

  // ---------------- OPTIMIZE PDF ----------------
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    category: 'optimize',
    description: 'Reduce file size while preserving high visual quality for emailing and sharing.',
    iconName: 'FileArchive',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['compress', 'shrink', 'size', 'reduce', 'optimize', 'email'],
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    slug: 'repair-pdf',
    category: 'optimize',
    description: 'Diagnose and reconstruct corrupted, unreadable, or damaged PDF documents.',
    iconName: 'Wrench',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['repair', 'fix', 'recover', 'corrupt', 'damaged'],
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    slug: 'ocr-pdf',
    category: 'optimize',
    description: 'Extract text from scanned documents and images to make them fully searchable.',
    iconName: 'FileSearch',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf', '.jpg', '.png'],
    keywords: ['ocr', 'text recognition', 'scanned', 'searchable', 'amharic', 'english'],
  },

  // ---------------- CONVERT TO PDF ----------------
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    category: 'convert-to',
    description: 'Convert JPG, PNG, WEBP, and BMP images into a clean, uniform PDF document.',
    iconName: 'Image',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.jpg', '.jpeg', '.png', '.webp', '.bmp'],
    keywords: ['jpg', 'png', 'image', 'picture', 'photos', 'photo to pdf'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    slug: 'word-to-pdf',
    category: 'convert-to',
    description: 'Convert Microsoft Word documents (.docx) into pristine, universal PDF files.',
    iconName: 'FileType2',
    clientSide: true,
    supportedInputTypes: ['.docx', '.doc'],
    keywords: ['word', 'docx', 'doc', 'microsoft word', 'document'],
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    slug: 'powerpoint-to-pdf',
    category: 'convert-to',
    description: 'Convert PowerPoint slide presentations (.pptx) into printable PDF format.',
    iconName: 'Presentation',
    clientSide: true,
    supportedInputTypes: ['.pptx', '.ppt'],
    keywords: ['powerpoint', 'pptx', 'presentation', 'slides'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    slug: 'excel-to-pdf',
    category: 'convert-to',
    description: 'Transform Excel spreadsheets (.xlsx) into clean, neatly formatted PDF tables.',
    iconName: 'Sheet',
    clientSide: true,
    supportedInputTypes: ['.xlsx', '.xls', '.csv'],
    keywords: ['excel', 'xlsx', 'spreadsheet', 'csv', 'sheets'],
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    slug: 'html-to-pdf',
    category: 'convert-to',
    description: 'Convert raw HTML code or web page markup into a structured PDF document.',
    iconName: 'Code',
    clientSide: true,
    supportedInputTypes: ['.html', '.htm'],
    keywords: ['html', 'webpage', 'code', 'url', 'markup'],
  },

  // ---------------- CONVERT FROM PDF ----------------
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    category: 'convert-from',
    description: 'Extract every page of a PDF as high-resolution JPG or PNG images with ZIP download.',
    iconName: 'Images',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['pdf to jpg', 'pdf to image', 'png', 'extract images', 'render'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    slug: 'pdf-to-word',
    category: 'convert-from',
    description: 'Convert PDF documents into editable Word (.docx) files preserving paragraphs.',
    iconName: 'FileText',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['pdf to word', 'docx', 'editable', 'text', 'export word'],
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    slug: 'pdf-to-powerpoint',
    category: 'convert-from',
    description: 'Transform PDF pages into editable PowerPoint (.pptx) presentation slides.',
    iconName: 'Presentation',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['pdf to ppt', 'powerpoint', 'slides', 'presentation'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    slug: 'pdf-to-excel',
    category: 'convert-from',
    description: 'Extract tables and structured numerical data from PDFs into Excel (.xlsx) spreadsheets.',
    iconName: 'Table',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['pdf to excel', 'spreadsheet', 'data', 'tables', 'csv'],
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    slug: 'pdf-to-pdfa',
    category: 'convert-from',
    description: 'Transform standard PDFs into ISO-compliant PDF/A format for long-term archiving.',
    iconName: 'ShieldCheck',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['pdf/a', 'archive', 'iso', 'compliance', 'preservation'],
  },

  // ---------------- EDIT PDF ----------------
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    category: 'edit',
    description: 'Rotate PDF pages 90°, 180°, or 270° clockwise or counter-clockwise permanently.',
    iconName: 'RotateCw',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['rotate', 'turn', 'orientation', 'landscape', 'portrait', 'flip'],
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    slug: 'add-page-numbers',
    category: 'edit',
    description: 'Insert customizable page numbers with custom positions, formats, and offsets.',
    iconName: 'Binary',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['page numbers', 'pagination', 'numbering', 'footer', 'header'],
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    slug: 'add-watermark',
    category: 'edit',
    description: 'Stamp custom confidential, draft, or copyright text watermarks across pages.',
    iconName: 'Stamp',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['watermark', 'stamp', 'confidential', 'draft', 'overlay', 'branding'],
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    slug: 'crop-pdf',
    category: 'edit',
    description: 'Trim margins and crop document pages to focus on specific content or tables.',
    iconName: 'Crop',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['crop', 'trim', 'margins', 'cut', 'resize'],
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    slug: 'edit-pdf',
    category: 'edit',
    description: 'Add free text, shapes, highlights, drawings, and annotations onto document pages.',
    iconName: 'PenTool',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['edit', 'annotate', 'draw', 'text', 'highlight', 'shapes'],
  },
  {
    id: 'pdf-forms',
    name: 'PDF Forms',
    slug: 'pdf-forms',
    category: 'edit',
    description: 'Fill interactive PDF form fields, text inputs, checkboxes, and export filled data.',
    iconName: 'CheckSquare',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['form', 'fill', 'interactive', 'fields', 'acroform'],
  },

  // ---------------- PDF SECURITY ----------------
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    slug: 'protect-pdf',
    category: 'security',
    description: 'Encrypt your PDF with strong user passwords and restrict unauthorized access.',
    iconName: 'Lock',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['protect', 'password', 'encrypt', 'security', 'lock'],
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    slug: 'unlock-pdf',
    category: 'security',
    description: 'Remove password restrictions from protected PDFs when authorized.',
    iconName: 'Unlock',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['unlock', 'decrypt', 'password remove', 'remove restriction'],
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    slug: 'sign-pdf',
    category: 'security',
    description: 'Draw or type your signature and place it securely on contracts and agreements.',
    iconName: 'FileSignature',
    badge: 'Popular',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['sign', 'signature', 'contract', 'initial', 'draw signature'],
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    slug: 'redact-pdf',
    category: 'security',
    description: 'Permanently blackout and sanitize sensitive personal data and numbers.',
    iconName: 'EyeOff',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['redact', 'blackout', 'sanitize', 'privacy', 'censor', 'erase'],
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    slug: 'compare-pdf',
    category: 'security',
    description: 'Visually compare two PDF versions side-by-side to pinpoint revisions and edits.',
    iconName: 'Columns2',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['compare', 'diff', 'versions', 'side by side', 'changes'],
  },

  // ---------------- PDF INTELLIGENCE ----------------
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    slug: 'ai-summarizer',
    category: 'intelligence',
    description: 'Generate structured executive overviews, key takeaways, and study questions.',
    iconName: 'Sparkles',
    badge: 'AI',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['ai', 'summarize', 'summary', 'overview', 'key points', 'study questions'],
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    slug: 'translate-pdf',
    category: 'intelligence',
    description: 'Translate PDF document text into English, Amharic, and other languages.',
    iconName: 'Languages',
    badge: 'AI',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['translate', 'translation', 'amharic', 'language', 'ai'],
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    slug: 'pdf-to-markdown',
    category: 'intelligence',
    description: 'Convert PDF document hierarchy into clean, structured Markdown for notes and wikis.',
    iconName: 'FileCode',
    badge: 'AI',
    clientSide: true,
    supportedInputTypes: ['.pdf'],
    keywords: ['markdown', 'md', 'structure', 'headings', 'obsidian', 'notion'],
  },
];

export const POPULAR_TOOL_SLUGS = [
  'pdf-unit-cutter',
  'merge-pdf',
  'split-pdf',
  'compress-pdf',
  'pdf-to-word',
  'jpg-to-pdf',
  'ocr-pdf',
  'ai-summarizer',
];

export function getToolBySlug(slug: string): ToolItem | undefined {
  return ALL_TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(cat: ToolCategory): ToolItem[] {
  return ALL_TOOLS.filter((t) => t.category === cat);
}

export function getPopularTools(): ToolItem[] {
  return POPULAR_TOOL_SLUGS.map((slug) => getToolBySlug(slug)!).filter(Boolean);
}
