import { getPdfJs, getPdfJsDocumentParams } from '../pdfReader';
import { getAIProvider, DocumentSummaryResult } from '../ai/aiProvider';

export interface ChunkedSummaryResult {
  engineLabel: string;
  summary: DocumentSummaryResult;
  totalPages: number;
  pagesAnalyzed: number;
  isScannedWarning: boolean;
  progressMessage: string;
}

/**
 * Progressively extracts and summarizes text from PDF documents in batches.
 * Honestly labeled as Local Document Summarizer unless an external model is configured.
 */
export async function summarizePdfDocument(
  pdfBuffer: ArrayBuffer,
  baseName: string,
  onProgress?: (percent: number, status: string) => void
): Promise<ChunkedSummaryResult> {
  onProgress?.(5, 'Opening PDF for progressive layout analysis...');

  const pdfjs = await getPdfJs();
  const loadingTask = pdfjs.getDocument(getPdfJsDocumentParams(pdfBuffer));
  const doc = await loadingTask.promise;
  const totalPages = doc.numPages;

  const chunkSize = 10;
  const totalChunks = Math.ceil(totalPages / chunkSize);
  let aggregatedText = '';
  let pagesAnalyzed = 0;

  for (let chunkIdx = 0; chunkIdx < totalChunks; chunkIdx++) {
    const startPage = chunkIdx * chunkSize + 1;
    const endPage = Math.min(totalPages, (chunkIdx + 1) * chunkSize);
    const progressStatus = `Analyzing pages ${startPage}–${endPage} of ${totalPages}...`;
    const pct = Math.round(10 + (chunkIdx / totalChunks) * 70);

    onProgress?.(pct, progressStatus);

    for (let p = startPage; p <= endPage; p++) {
      try {
        const page = await doc.getPage(p);
        const textContent = await page.getTextContent();
        const pageStr = (textContent.items || []).map((it: any) => it.str || '').join(' ').trim();
        if (pageStr) {
          aggregatedText += `\n[Page ${p}]\n` + pageStr;
          pagesAnalyzed++;
        }
      } catch {
        // Continue with remaining pages if one fails
      }
    }
  }

  const isScannedWarning = aggregatedText.trim().length === 0;

  if (isScannedWarning) {
    onProgress?.(100, 'Scan analysis complete (No selectable text).');
    return {
      engineLabel: 'Local Document Summarizer (Rule-Based & Heuristic Extraction)',
      summary: {
        overview: 'This document appears to be scanned or contains only images. No selectable text could be extracted. Please run OCR PDF first to generate a searchable text layer before summarizing.',
        keyPoints: ['No extractable text layer detected in document streams.'],
        sectionSummaries: [],
        keyDefinitions: [],
        studyQuestions: [],
      },
      totalPages,
      pagesAnalyzed: 0,
      isScannedWarning: true,
      progressMessage: '0 selectable text pages detected. OCR required.',
    };
  }

  onProgress?.(85, 'Synthesizing structured executive overview and key concepts...');

  const provider = getAIProvider();
  const summary = await provider.summarizeDocument(aggregatedText, baseName);

  onProgress?.(100, `Pages analyzed: ${pagesAnalyzed} / ${totalPages}`);

  return {
    engineLabel: 'Local Document Summarizer (Rule-Based & Heuristic Extraction)',
    summary,
    totalPages,
    pagesAnalyzed,
    isScannedWarning: false,
    progressMessage: `Pages analyzed: ${pagesAnalyzed} / ${totalPages}`,
  };
}

export function formatSummaryAsMarkdown(res: ChunkedSummaryResult, title: string): string {
  const s = res.summary;
  let md = `# Executive Document Summary: ${title}\n\n`;
  md += `*Generated by DocuNexa ${res.engineLabel}*\n\n`;
  md += `## Overview\n${s.overview}\n\n`;

  if (s.keyPoints && s.keyPoints.length > 0) {
    md += `## Key Takeaways\n`;
    s.keyPoints.forEach((kp) => {
      md += `- ${kp}\n`;
    });
    md += `\n`;
  }

  if (s.sectionSummaries && s.sectionSummaries.length > 0) {
    md += `## Section Outlines\n`;
    s.sectionSummaries.forEach((sec) => {
      md += `### ${sec.title}\n${sec.summary}\n\n`;
    });
  }

  if (s.keyDefinitions && s.keyDefinitions.length > 0) {
    md += `## Core Concept Definitions\n`;
    s.keyDefinitions.forEach((d) => {
      md += `- **${d.term}**: ${d.definition}\n`;
    });
    md += `\n`;
  }

  if (s.studyQuestions && s.studyQuestions.length > 0) {
    md += `## Review & Study Questions\n`;
    s.studyQuestions.forEach((q, idx) => {
      md += `${idx + 1}. ${q}\n`;
    });
    md += `\n`;
  }

  return md;
}

export function formatSummaryAsPlainText(res: ChunkedSummaryResult, title: string): string {
  const s = res.summary;
  let txt = `EXECUTIVE DOCUMENT SUMMARY: ${title.toUpperCase()}\n`;
  txt += `Generated by DocuNexa ${res.engineLabel}\n`;
  txt += `================================================================\n\n`;
  txt += `OVERVIEW:\n${s.overview}\n\n`;

  if (s.keyPoints && s.keyPoints.length > 0) {
    txt += `KEY TAKEAWAYS:\n`;
    s.keyPoints.forEach((kp) => {
      txt += `  * ${kp}\n`;
    });
    txt += `\n`;
  }

  if (s.sectionSummaries && s.sectionSummaries.length > 0) {
    txt += `SECTION BREAKDOWNS:\n`;
    s.sectionSummaries.forEach((sec) => {
      txt += `[${sec.title}]\n${sec.summary}\n\n`;
    });
  }

  if (s.keyDefinitions && s.keyDefinitions.length > 0) {
    txt += `CORE DEFINITIONS:\n`;
    s.keyDefinitions.forEach((d) => {
      txt += `  * ${d.term}: ${d.definition}\n`;
    });
    txt += `\n`;
  }

  if (s.studyQuestions && s.studyQuestions.length > 0) {
    txt += `STUDY QUESTIONS:\n`;
    s.studyQuestions.forEach((q, idx) => {
      txt += `  ${idx + 1}. ${q}\n`;
    });
    txt += `\n`;
  }

  return txt;
}
